{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "distcc.serviceAccountName" . }}
  labels:
{{ include "distcc.labels" . | indent 4 }}
{{- end -}}
