apiVersion: v1
kind: Service
metadata:
  name: status
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.status.port }}
      targetPort: status
      protocol: TCP
      name: status
  selector:
    app.kubernetes.io/name: {{ include "distcc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
